name: rl_exercises
channels:
    - conda-forge
    - pytorch
dependencies:
  - imageio==2.37.0
  - ipywidgets=8.1.3
  - jupyterlab=4.2.3
  - matplotlib=3.8.2
  - numpy=1.24.4
  - pip=22.0.4
  - python=3.10.0
  - pytorch=2.6.0
  - tqdm=4.66.0
  - pip:
    - gymnasium==1.2.0
    - gymnasium[box2d]
    - imageio[ffmpeg]